### ISSUE TITLE
Burger-Menü verschwunden?

### ISSUE THREAD

**Issue by thomashuckert** [abatplus/bumpit_mobile#25]
Habe die App gestartet und finde das Burger-Menü nicht. (Siehe Screenshot)
![image](https://user-images.githubusercontent.com/51959504/87669071-9a299300-c76d-11ea-866e-03eec69b5843.png)

**Comment by michaeltheobald** [comment]
Wenn man den Browser schmal genug zieht, ist es wieder da. Das könnte bei Tablets zu Problemen führen.
